import type { WeatherCodeInformation } from "./weather_code";

type DailyMapping = {
    time: string,
    values: {
        weatherCodeInfo: WeatherCodeInformation,
        sunsetTime : string
        uvIndexAvg : number,
        uvIndexMax : number,
        uvIndexMin : number,
        dewPointAvg : number,
        dewPointMax : number,
        dewPointMin : number,
        humidityAvg : number,
        humidityMax : number,
        humidityMin : number,
        moonsetTime : string,
        sunriseTime : string,
        windGustAvg : number,
        windGustMax : number,
        windGustMin : number,
        cloudBaseAvg : number,
        cloudBaseMax : number,
        cloudBaseMin : number,
        moonriseTime : string,
        snowDepthAvg : number,
        snowDepthMax : number,
        snowDepthMin : number,
        snowDepthSum : number,
        windSpeedAvg : number,
        windSpeedMax : number,
        windSpeedMin : number,
        cloudCoverAvg : number,
        cloudCoverMax : number,
        cloudCoverMin : number,
        visibilityAvg : number,
        visibilityMax : number,
        visibilityMin : number,
        temperatureAvg : number,
        temperatureMax : number,
        temperatureMin : number,
        weatherCodeMax : number,
        weatherCodeMin : number,
        cloudCeilingAvg : number,
        cloudCeilingMax : number,
        cloudCeilingMin : number,
        rainIntensityAvg : number,
        rainIntensityMax :  number,
        rainIntensityMin : number,
        snowIntensityAvg : number,
        snowIntensityMax : number,
        snowIntensityMin : number,
        windDirectionAvg : number,
        sleetIntensityAvg : number,
        sleetIntensityMax : number,
        sleetIntensityMin : number,
        iceAccumulationAvg : number,
        iceAccumulationMax : number,
        iceAccumulationMin : number,
        iceAccumulationSum : number,
        uvHealthConcernAvg : number,
        uvHealthConcernMax : number,
        uvHealthConcernMin : number,
        rainAccumulationAvg : number,
        rainAccumulationMax : number,
        rainAccumulationMin : number,
        rainAccumulationSum : number,
        snowAccumulationAvg : number,
        snowAccumulationMax : number,
        snowAccumulationMin : number,
        snowAccumulationSum : number,
        sleetAccumulationAvg : number,
        sleetAccumulationMax : number,
        sleetAccumulationMin : number,
        evapotranspirationAvg : number,
        evapotranspirationMax : number,
        evapotranspirationMin : number,
        evapotranspirationSum : number,
        iceAccumulationLweAvg : number,
        iceAccumulationLweMax : number,
        iceAccumulationLweMin : number,
        iceAccumulationLweSum : number,
        rainAccumulationLweAvg : number,
        rainAccumulationLweMax : number,
        rainAccumulationLweMin : number,
        snowAccumulationLweAvg : number,
        snowAccumulationLweMax : number,
        snowAccumulationLweMin : number,
        snowAccumulationLweSum : number,
        temperatureApparentAvg : number,
        temperatureApparentMax : number,
        temperatureApparentMin : number,
        pressureSurfaceLevelAvg : number,
        pressureSurfaceLevelMax : number,
        pressureSurfaceLevelMin : number,
        sleetAccumulationLweAvg : number,
        sleetAccumulationLweMax : number,
        sleetAccumulationLweMin : number,
        sleetAccumulationLweSum : number,
        freezingRainIntensityAvg : number,
        freezingRainIntensityMax : number,
        freezingRainIntensityMin : number,
        precipitationProbabilityAvg : number,
        precipitationProbabilityMax : number,
        precipitationProbabilityMin : number 
    }
}

type TomorrowIoForecast = {
    response: {
        location: {
            lat: number,
            long: number
        }
        timelines: {
            daily: DailyMapping[]
        }
    },
    place_id: string,
    cached: boolean
}

export type { TomorrowIoForecast };