# Generated by Django 4.2.6 on 2023-10-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomorrowiorequest',
            name='requestedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
