# Generated by Django 4.2.6 on 2023-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_tomorrowiorequest_requestedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomorrowiorequest',
            name='requestQuery',
        ),
        migrations.AddField(
            model_name='tomorrowiorequest',
            name='locationQuery',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomorrowiorequest',
            name='timesteps',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomorrowiorequest',
            name='units',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
