# Generated by Django 4.2.6 on 2023-11-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_tomorrowiorequest_timesteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomorrowiorequest',
            name='locationName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tomorrowiorequest',
            name='locationType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
