# Generated by Django 4.2.6 on 2023-11-17 17:38

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_tomorrowiorequest_locationname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=10)),
                ('formattedAddress', models.CharField(max_length=400)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleMapApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('placeId', models.CharField(max_length=100)),
                ('locationType', models.CharField(max_length=100, null=True)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='weather.address')),
            ],
            options={
                'indexes': [models.Index(fields=['placeId', 'createdAt'], name='gmar_placeId_createdAt_idx')],
            },
        ),
    ]
