# Generated by Django 4.2.6 on 2023-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_address_googlemapapirequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlemapapirequest',
            name='apiResult',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='formattedAddress',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
