# Generated by Django 4.2.6 on 2023-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_address_county_googlemapapirequest_apiresult_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='googlemapapirequest',
            name='gmar_placeId_createdAt_idx',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address3',
            new_name='address_3',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='formattedAddress',
            new_name='formatted_address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='googlemapapirequest',
            old_name='apiResult',
            new_name='api_result',
        ),
        migrations.RenameField(
            model_name='googlemapapirequest',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='googlemapapirequest',
            old_name='locationType',
            new_name='location_type',
        ),
        migrations.RenameField(
            model_name='googlemapapirequest',
            old_name='placeId',
            new_name='place_id',
        ),
        migrations.RenameField(
            model_name='tomorrowiorequest',
            old_name='locationName',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='tomorrowiorequest',
            old_name='locationQuery',
            new_name='location_query',
        ),
        migrations.RenameField(
            model_name='tomorrowiorequest',
            old_name='locationType',
            new_name='location_type',
        ),
        migrations.RenameField(
            model_name='tomorrowiorequest',
            old_name='requestedAt',
            new_name='requested_at',
        ),
        migrations.RenameField(
            model_name='tomorrowiorequest',
            old_name='returnData',
            new_name='return_data',
        ),
        migrations.AddField(
            model_name='address',
            name='compound_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='global_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='plus_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='googlemapapirequest',
            index=models.Index(fields=['place_id', 'created_at'], name='gmar_placeId_createdAt_idx'),
        ),
    ]
