# Generated by Django 4.2.6 on 2024-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_remove_tomorrowiorequest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemapapirequest',
            name='place_id',
            field=models.CharField(max_length=150),
        ),
    ]
